---

- hosts: localhost

  tasks:

  - name: create a private network
    os_network:
      cloud: tacc
      external: no
      name: private

  - name: create a subnet within private network
    os_subnet: 
      state: present
      network_name: private
      name: private_subnet
      cidr: 10.0.0.0/24
      cloud: tacc
  
  - name: create a router on the private network
    os_router:
      cloud: tacc
      state: present
      name: simple_router
      network: public
      interfaces:
        - private_subnet
  
  - name: build blank nodes 
    os_server:
      state: present
      name: '{{ item.hostname }}'
      cloud: tacc
      image: 1790e5c8-315a-4b9b-8b1f-46e47330d3cc
      key_name: jetstream_key
      timeout: 200
      flavor: m1.small
      meta:
        hostname: '{{ item.hostname }}'
        group: '{{ item.group }}'
      auto_ip: yes
      network: private
    with_items: # maybe this should go in group_vars?
      - { hostname: 'pga-test', group: 'pga' }
      - { hostname: 'zookeeper-test', group: 'zookeeper' }
      - { hostname: 'rabbitmq-test', group: 'rabbitmq' }
      - { hostname: 'database-test', group: 'database' }
      - { hostname: 'wso2is-test', group: 'wso2is' }
      - { hostname: 'gfac-test', group: 'gfac' }
      - { hostname: 'api-orch-test', group: 'api-orch' }
      - { hostname: 'registry-test', group: 'registry' }
