---

- hosts: localhost

  tasks:

  - name: create a private network
    os_network:
      cloud: tacc
      external: no
      name: private

  - name: create a subnet within private network
    os_subnet: 
      state: present
      network_name: private
      name: private_subnet
      cidr: 10.0.0.0/24
      cloud: tacc
  
  - name: create a router on the private network
    os_router:
      cloud: tacc
      state: present
      name: simple_router
      network: public
      interfaces:
        - private_subnet
  
  - name: build blank nodes 
    os_server:
      state: present
      name: test-vm-1
      cloud: tacc
      image: 1790e5c8-315a-4b9b-8b1f-46e47330d3cc
      key_name: jetstream_key
      timeout: 200
      flavor: m1.small
      meta:
        hostname: test-vm-1
      auto_ip: yes
      network: private
